### ISSUE TITLE
Suggestion: return result from post method

### ISSUE THREAD

**Issue by zhaoyao91** [rogierschouten/ts-events#19] opened 2020-02-23 10:48 UTC
Can it return a promise which resolves to the results listeners returned?

**Comment by rogierschouten** [comment] 2020-02-24 09:33
More or less a duplicate of #13.   I have no intention of implementing this myself currently but feel free to do a backwards-compatible PR.  Let's keep tracking this in #13.

**Closed as completed by rogierschouten** 2020-02-24 09:33 UTC
